services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: owox-postgres
    environment:
      POSTGRES_DB: owox_data_marts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - owox-network

  # Redis for Celery and Caching
  redis:
    image: redis:7-alpine
    container_name: owox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - owox-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: owox-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/owox_data_marts
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - postgres
      - redis
    networks:
      - owox-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: owox-celery-worker
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/owox_data_marts
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - postgres
      - redis
    networks:
      - owox-network
    command: celery -A app.tasks.celery_app worker --loglevel=info

  # Celery Beat (Scheduler)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: owox-celery-beat
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/owox_data_marts
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - postgres
      - redis
    networks:
      - owox-network
    command: celery -A app.tasks.celery_app beat --loglevel=info

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: owox-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - owox-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  owox-network:
    driver: bridge
