export enum DataMartRunType {
  CONNECTOR = 'CONNECTOR',
  GOOGLE_SHEETS_EXPORT = 'GOOGLE_SHEETS_EXPORT',
  LOOKER_STUDIO = 'LOOKER_STUDIO',
  EMAIL = 'EMAIL',
  SLACK = 'SLACK',
  MS_TEAMS = 'MS_TEAMS',
  GOOGLE_CHAT = 'GOOGLE_CHAT',
}
