export enum DataMartDefinitionType {
  SQL = 'SQL',
  TABLE = 'TABLE',
  VIEW = 'VIEW',
  TABLE_PATTERN = 'TABLE_PATTERN',
  CONNECTOR = 'CONNECTOR',
  LEGACY_EXTENSION_SQL = 'LEGACY_EXTENSION_SQL',
}
