/**
 * Copyright (c) OWOX, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

// API reference: https://shopify.dev/docs/api/admin-graphql/2025-01/objects/Order

var ordersFields = {
  'id': {
    'description': 'A globally-unique ID.',
    'type': 'string',
    'graphqlPath': 'id'
  },
  'name': {
    'description': 'The order name, generated by combining the order_number with the shop order prefix.',
    'type': 'string',
    'graphqlPath': 'name'
  },
  'email': {
    'description': 'The email address of the customer.',
    'type': 'string',
    'graphqlPath': 'email'
  },
  'phone': {
    'description': 'The phone number of the customer.',
    'type': 'string',
    'graphqlPath': 'phone'
  },
  'displayFinancialStatus': {
    'description': 'The financial status of the order.',
    'type': 'string',
    'graphqlPath': 'displayFinancialStatus'
  },
  'displayFulfillmentStatus': {
    'description': 'The fulfillment status of the order.',
    'type': 'string',
    'graphqlPath': 'displayFulfillmentStatus'
  },
  'confirmed': {
    'description': 'Whether the order is confirmed.',
    'type': 'bool',
    'graphqlPath': 'confirmed'
  },
  'closed': {
    'description': 'Whether the order is closed.',
    'type': 'bool',
    'graphqlPath': 'closed'
  },
  'cancelledAt': {
    'description': 'The date and time when the order was cancelled.',
    'type': 'timestamp',
    'graphqlPath': 'cancelledAt'
  },
  'cancelReason': {
    'description': 'The reason for cancellation.',
    'type': 'string',
    'graphqlPath': 'cancelReason'
  },
  'currencyCode': {
    'description': 'The currency of the order.',
    'type': 'string',
    'graphqlPath': 'currencyCode'
  },
  'subtotalPrice': {
    'description': 'The subtotal price of the order.',
    'type': 'float',
    'graphqlPath': 'subtotalPriceSet { shopMoney { amount } }'
  },
  'totalPrice': {
    'description': 'The total price of the order.',
    'type': 'float',
    'graphqlPath': 'totalPriceSet { shopMoney { amount } }'
  },
  'totalTax': {
    'description': 'The total tax of the order.',
    'type': 'float',
    'graphqlPath': 'totalTaxSet { shopMoney { amount } }'
  },
  'totalShippingPrice': {
    'description': 'The total shipping price.',
    'type': 'float',
    'graphqlPath': 'totalShippingPriceSet { shopMoney { amount } }'
  },
  'totalDiscounts': {
    'description': 'The total discounts applied.',
    'type': 'float',
    'graphqlPath': 'totalDiscountsSet { shopMoney { amount } }'
  },
  'totalRefunded': {
    'description': 'The total amount refunded.',
    'type': 'float',
    'graphqlPath': 'totalRefundedSet { shopMoney { amount } }'
  },
  'totalWeight': {
    'description': 'The total weight of the order.',
    'type': 'float',
    'graphqlPath': 'totalWeight'
  },
  'lineItemsCount': {
    'description': 'The number of line items.',
    'type': 'int32',
    'graphqlPath': 'lineItems { nodes { id } }'
  },
  'fullyPaid': {
    'description': 'Whether the order is fully paid.',
    'type': 'bool',
    'graphqlPath': 'fullyPaid'
  },
  'taxesIncluded': {
    'description': 'Whether taxes are included in the order subtotal.',
    'type': 'bool',
    'graphqlPath': 'taxesIncluded'
  },
  'taxExempt': {
    'description': 'Whether the order is tax exempt.',
    'type': 'bool',
    'graphqlPath': 'taxExempt'
  },
  'customerId': {
    'description': 'The ID of the customer.',
    'type': 'string',
    'graphqlPath': 'customer { id }'
  },
  'customerEmail': {
    'description': 'The email of the customer.',
    'type': 'string',
    'graphqlPath': 'customer { email }'
  },
  'shippingAddressCity': {
    'description': 'City from the shipping address.',
    'type': 'string',
    'graphqlPath': 'shippingAddress { city }'
  },
  'shippingAddressCountry': {
    'description': 'Country from the shipping address.',
    'type': 'string',
    'graphqlPath': 'shippingAddress { country }'
  },
  'shippingAddressProvince': {
    'description': 'Province from the shipping address.',
    'type': 'string',
    'graphqlPath': 'shippingAddress { province }'
  },
  'shippingAddressZip': {
    'description': 'Postal/ZIP code from the shipping address.',
    'type': 'string',
    'graphqlPath': 'shippingAddress { zip }'
  },
  'billingAddressCity': {
    'description': 'City from the billing address.',
    'type': 'string',
    'graphqlPath': 'billingAddress { city }'
  },
  'billingAddressCountry': {
    'description': 'Country from the billing address.',
    'type': 'string',
    'graphqlPath': 'billingAddress { country }'
  },
  'billingAddressProvince': {
    'description': 'Province from the billing address.',
    'type': 'string',
    'graphqlPath': 'billingAddress { province }'
  },
  'billingAddressZip': {
    'description': 'Postal/ZIP code from the billing address.',
    'type': 'string',
    'graphqlPath': 'billingAddress { zip }'
  },
  'tags': {
    'description': 'A comma-separated list of tags.',
    'type': 'string',
    'graphqlPath': 'tags'
  },
  'note': {
    'description': 'The note attached to the order.',
    'type': 'string',
    'graphqlPath': 'note'
  },
  'sourceName': {
    'description': 'The source of the order.',
    'type': 'string',
    'graphqlPath': 'sourceName'
  },
  'processedAt': {
    'description': 'The date and time when the order was processed.',
    'type': 'timestamp',
    'graphqlPath': 'processedAt'
  },
  'closedAt': {
    'description': 'The date and time when the order was closed.',
    'type': 'timestamp',
    'graphqlPath': 'closedAt'
  },
  'createdAt': {
    'description': 'The date and time when the order was created.',
    'type': 'timestamp',
    'graphqlPath': 'createdAt'
  },
  'updatedAt': {
    'description': 'The date and time when the order was last updated.',
    'type': 'timestamp',
    'graphqlPath': 'updatedAt'
  }
};
