"""add_new_storage_destination_types

Revision ID: 02b1644a3a5b
Revises: e365fb6c1e3c
Create Date: 2025-09-29 10:30:07.243563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b1644a3a5b'
down_revision = 'e365fb6c1e3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
