"""Add destination_id to DataMart

Revision ID: 45f5e1dea70c
Revises: 7bdefed9d1c9
Create Date: 2025-09-26 11:56:21.547549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f5e1dea70c'
down_revision = '7bdefed9d1c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_marts', sa.Column('destination_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'data_marts', 'data_destinations', ['destination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_marts', type_='foreignkey')
    op.drop_column('data_marts', 'destination_id')
    # ### end Alembic commands ###
