"""Add scheduled jobs table

Revision ID: 8cfc9bd2a80c
Revises: bf8c1765ffa6
Create Date: 2025-09-29 13:33:35.984770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cfc9bd2a80c'
down_revision = 'bf8c1765ffa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('schedule_config', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution_status', sa.String(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['data_connectors.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_connector_id'), 'scheduled_jobs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_id'), 'scheduled_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_name'), 'scheduled_jobs', ['name'], unique=False)
    op.drop_table('analytics_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctr', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transferred_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='analytics_data_pkey')
    )
    op.drop_index(op.f('ix_scheduled_jobs_name'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_connector_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
