"""make_data_mart_storage_id_nullable

Revision ID: bde23ee1ae54
Revises: f3b5fe9b9e09
Create Date: 2025-09-30 11:44:16.024249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bde23ee1ae54'
down_revision = 'f3b5fe9b9e09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_job_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('extracted_records', sa.Integer(), nullable=True),
    sa.Column('transformed_records', sa.Integer(), nullable=True),
    sa.Column('loaded_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('source_collection_name', sa.String(length=255), nullable=True),
    sa.Column('destination_name', sa.String(length=255), nullable=True),
    sa.Column('destination_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['data_connectors.id'], ),
    sa.ForeignKeyConstraint(['scheduled_job_id'], ['scheduled_jobs.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_runs_connector_id'), 'connector_runs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_runs_execution_id'), 'connector_runs', ['execution_id'], unique=True)
    op.create_index(op.f('ix_connector_runs_id'), 'connector_runs', ['id'], unique=False)
    op.create_index(op.f('ix_connector_runs_scheduled_job_id'), 'connector_runs', ['scheduled_job_id'], unique=False)
    op.drop_table('analytics_data')
    op.alter_column('data_marts', 'storage_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_marts', 'storage_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('analytics_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctr', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('transferred_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='analytics_data_pkey')
    )
    op.drop_index(op.f('ix_connector_runs_scheduled_job_id'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_id'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_execution_id'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_connector_id'), table_name='connector_runs')
    op.drop_table('connector_runs')
    # ### end Alembic commands ###
