"""add_data_connector_model

Revision ID: bf8c1765ffa6
Revises: 5e4698f32028
Create Date: 2025-09-29 12:50:26.407766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c1765ffa6'
down_revision = '5e4698f32028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_collection_id', sa.String(), nullable=False),
    sa.Column('source_collection_name', sa.String(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('destination_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution_status', sa.String(), nullable=True),
    sa.Column('records_transferred', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_connectors_destination_id'), 'data_connectors', ['destination_id'], unique=False)
    op.create_index(op.f('ix_data_connectors_id'), 'data_connectors', ['id'], unique=False)
    op.create_index(op.f('ix_data_connectors_name'), 'data_connectors', ['name'], unique=False)
    op.create_index(op.f('ix_data_connectors_source_collection_id'), 'data_connectors', ['source_collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_connectors_source_collection_id'), table_name='data_connectors')
    op.drop_index(op.f('ix_data_connectors_name'), table_name='data_connectors')
    op.drop_index(op.f('ix_data_connectors_id'), table_name='data_connectors')
    op.drop_index(op.f('ix_data_connectors_destination_id'), table_name='data_connectors')
    op.drop_table('data_connectors')
    # ### end Alembic commands ###
