"""add_storage_frontend_compatibility_fields

Revision ID: e365fb6c1e3c
Revises: 90eab826b4b6
Create Date: 2025-09-29 10:10:03.892712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e365fb6c1e3c'
down_revision = '90eab826b4b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_destinations', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('data_destinations', sa.Column('storage_type', sa.String(length=100), nullable=True))
    op.add_column('data_destinations', sa.Column('configuration', sa.JSON(), nullable=True))
    op.add_column('data_destinations', sa.Column('unique_key_columns', sa.JSON(), nullable=True))
    op.add_column('data_destinations', sa.Column('schema_definition', sa.JSON(), nullable=True))
    op.add_column('data_destinations', sa.Column('platform_credential_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_destinations', 'platform_credential_id')
    op.drop_column('data_destinations', 'schema_definition')
    op.drop_column('data_destinations', 'unique_key_columns')
    op.drop_column('data_destinations', 'configuration')
    op.drop_column('data_destinations', 'storage_type')
    op.drop_column('data_destinations', 'name')
    # ### end Alembic commands ###
