"""Add project_id to User model

Revision ID: e5c402270109
Revises: 45f5e1dea70c
Create Date: 2025-09-26 11:57:37.079321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c402270109'
down_revision = '45f5e1dea70c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'project_id')
    # ### end Alembic commands ###
