"""Create user and related tables

Revision ID: ebc7f454c473
Revises: 1decad7b3e5e
Create Date: 2025-09-22 14:03:17.991047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc7f454c473'
down_revision = '1decad7b3e5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
