import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import type { AssistantProposedAction } from '../../ai-insights/agent-flow/ai-assistant-types';
import { AiAssistantMessageRole } from '../../enums/ai-assistant-message-role.enum';
import { AiAssistantMessageApplyStatus } from '../domain/ai-assistant-message.dto';

export class AiAssistantMessageResponseApiDto {
  @ApiProperty({ example: '4fce612f-6a4c-4ccf-a97d-92c69fd6230a' })
  id: string;

  @ApiProperty({ example: 'e7f7e087-2042-4de0-b1fc-67dddbaf88dd' })
  sessionId: string;

  @ApiProperty({
    enum: AiAssistantMessageRole,
    enumName: 'AiAssistantMessageRole',
    example: AiAssistantMessageRole.USER,
  })
  role: AiAssistantMessageRole;

  @ApiProperty({ example: 'Show monthly consumption by product for 2025' })
  content: string;

  @ApiPropertyOptional({
    type: 'array',
    items: { type: 'object' },
    nullable: true,
    description: 'Explicit list of available actions proposed by the assistant',
  })
  proposedActions?: AssistantProposedAction[] | null;

  @ApiPropertyOptional({
    nullable: true,
    description: 'SQL candidate generated by assistant for apply/preview',
    example: 'SELECT date, SUM(revenue) FROM orders GROUP BY date',
  })
  sqlCandidate?: string | null;

  @ApiProperty({
    enum: AiAssistantMessageApplyStatus,
    enumName: 'AiAssistantMessageApplyStatus',
    example: AiAssistantMessageApplyStatus.PENDING,
    description: 'Apply lifecycle state for this assistant message',
  })
  applyStatus: AiAssistantMessageApplyStatus;

  @ApiPropertyOptional({
    nullable: true,
    example: '2026-02-20T18:20:00.000Z',
    description: 'Timestamp of successful apply',
  })
  appliedAt?: string | Date | null;

  @ApiPropertyOptional({
    nullable: true,
    example: 'act_123',
    description: 'Action request id that was applied',
  })
  appliedRequestId?: string | null;

  @ApiProperty({ example: '2026-02-15T16:10:06.930Z' })
  createdAt: string | Date;
}
